# app/utils/query_generator.py
# ─────────────────────────────────────────────────────────────────────────────
# Intelligent query generator for brand visibility monitoring.
#
# WHAT MAKES THIS "HUMAN-LIKE":
#
#   Real people search in wildly different ways:
#     - Short fragments:      "best laptop under 500"
#     - Full questions:       "what is the best laptop for college students"
#     - Conversational:       "i need a cheap laptop that actually works"
#     - With typos:           "laaptop with good baterry life"
#     - Reddit-style:         "laptop recommendations reddit 2026"
#     - Comparison seeking:   "ebay vs amazon refurbished phones"
#     - Review hunting:       "ebay refurbished phone honest review"
#     - Frustrated:           "why is ebay so expensive now"
#
#   This system models 8 distinct "searcher personas", each with their own
#   vocabulary, phrasing style, and search habits. A query is generated by
#   picking a persona, then filling its pattern with contextual profile data.
#
# WEIGHT SYSTEM:
#   70% branded   — brand name appears naturally in query
#   25% unbranded — generic consumer search, no brand name
#    5% competitor — brand appears in a vs/comparison context
#
# PRODUCT FOCUS:
#   Every single query is shaped by the `product` argument.
#   Pass "mobile" and every query is about mobile. No exceptions.
#
# NO LLM USED.
# ─────────────────────────────────────────────────────────────────────────────

import random
import time
from dataclasses import dataclass, field
from typing import Optional


# ─────────────────────────────────────────────────────────────────────────────
# COMPANY PROFILES
# ─────────────────────────────────────────────────────────────────────────────

COMPANY_PROFILES = {

    "capital one": {
        "display_name": "Capital One",
        "owned_by": "Bre'Ann",
        "industry": "financial_services",
        "competitors": ["Chase", "American Express", "Citi", "Discover",
                        "Bank of America", "Wells Fargo", "Ally Bank",
                        "Marcus by Goldman Sachs", "Navy Federal", "US Bank"],
        "price_anchors": ["$0 annual fee", "$95 annual fee", "$395 annual fee",
                          "0% intro APR", "low APR", "no foreign transaction fees",
                          "under $100 annual fee"],
        "attributes": ["cash back rate", "sign-up bonus", "travel rewards",
                       "credit limit", "APR", "mobile app quality",
                       "fraud protection", "credit score requirement",
                       "airport lounge access", "no foreign transaction fees",
                       "balance transfer offer", "customer service"],
        "use_contexts": ["building credit from scratch",
                         "earning travel rewards",
                         "getting cash back on groceries",
                         "doing a balance transfer",
                         "financing a car",
                         "opening a high yield savings account",
                         "earning a big welcome bonus",
                         "booking flights and hotels",
                         "everyday spending",
                         "dining out",
                         "running a small business",
                         "studying abroad"],
        "customer_types": ["college students", "young professionals",
                           "frequent travelers", "small business owners",
                           "people rebuilding credit", "military families",
                           "first time card holders", "families", "freelancers"],
        "pain_points": ["high annual fee", "low credit limit",
                        "hard to get approved", "interest rate too high",
                        "rewards expiring", "foreign transaction fees"],
    },

    "ebay": {
        "display_name": "eBay",
        "owned_by": "Dharambir",
        "industry": "ecommerce_marketplace",
        "competitors": ["Amazon", "Mercari", "Facebook Marketplace", "Poshmark",
                        "OfferUp", "Craigslist", "StockX", "GOAT", "Etsy",
                        "Depop", "Swappa", "Walmart Marketplace", "Back Market"],
        "price_anchors": ["under $50", "under $100", "under $200", "under $300",
                          "under $500", "for cheap", "starting at $1",
                          "best price", "free shipping"],
        "attributes": ["buyer protection", "return policy", "seller ratings",
                       "authenticity guarantee", "free shipping",
                       "auction format", "best offer option",
                       "money back guarantee", "seller fees",
                       "how safe it is", "international shipping"],
        "use_contexts": ["buying used electronics",
                         "selling old stuff online",
                         "finding rare collectibles",
                         "buying a refurbished phone",
                         "flipping items for profit",
                         "finding vintage clothing",
                         "buying used auto parts",
                         "collecting trading cards",
                         "finding discontinued products",
                         "buying sneakers for less",
                         "buying wholesale lots"],
        "customer_types": ["bargain hunters", "collectors", "resellers",
                           "sneakerheads", "vintage shoppers", "hobbyists",
                           "small sellers", "car enthusiasts", "thrift shoppers",
                           "people on a tight budget"],
        "pain_points": ["getting scammed", "fake items", "seller not shipping",
                        "high seller fees", "difficult returns",
                        "counterfeit products", "item not as described"],
    },

    "heb": {
        "display_name": "H-E-B",
        "owned_by": "Elikem",
        "industry": "grocery_retail",
        "competitors": ["Walmart", "Kroger", "Costco", "Whole Foods",
                        "Trader Joe's", "Aldi", "Target", "Instacart",
                        "Amazon Fresh", "Sprouts", "Sam's Club"],
        "price_anchors": ["budget friendly", "under $50 a week", "best value",
                          "store brand savings", "weekly deals"],
        "attributes": ["fresh produce quality", "store brand quality", "prices",
                       "curbside pickup speed", "delivery reliability",
                       "organic selection", "prepared foods quality",
                       "weekly specials", "digital coupons", "customer service"],
        "use_contexts": ["weekly grocery shopping", "meal planning",
                         "buying organic on a budget",
                         "ordering groceries for pickup",
                         "quick weeknight dinners",
                         "holiday meal shopping",
                         "buying Texas made products",
                         "party food and catering"],
        "customer_types": ["Texas families", "budget shoppers",
                           "organic food fans", "meal preppers",
                           "busy parents", "health conscious shoppers",
                           "seniors", "college students in Texas"],
        "pain_points": ["long lines", "out of stock items", "delivery delays",
                        "app not working", "prices going up", "limited locations"],
    },

    "home depot": {
        "display_name": "Home Depot",
        "owned_by": "Tereik",
        "industry": "home_improvement",
        "competitors": ["Lowe's", "Menards", "Ace Hardware", "True Value",
                        "Wayfair", "Amazon", "Sherwin-Williams",
                        "Harbor Freight", "Northern Tool"],
        "price_anchors": ["under $50", "under $100", "under $200", "under $500",
                          "budget", "professional grade", "on sale", "clearance"],
        "attributes": ["product selection", "price match", "tool rental",
                       "installation services", "pro discounts",
                       "delivery speed", "in store pickup", "return policy",
                       "staff knowledge", "brand variety"],
        "use_contexts": ["kitchen renovation", "bathroom remodel",
                         "building a deck", "painting a room",
                         "installing new flooring", "landscaping",
                         "fence installation", "plumbing repair",
                         "electrical work", "garage organization",
                         "replacing a water heater"],
        "customer_types": ["homeowners", "DIY enthusiasts", "contractors",
                           "landlords", "first time home buyers", "renovators",
                           "gardeners", "house flippers"],
        "pain_points": ["hard to find staff", "out of stock", "long checkout lines",
                        "delivery damage", "installation booking takes too long"],
    },

    "dell": {
        "display_name": "Dell",
        "owned_by": "Daniel Enesi",
        "industry": "technology",
        "competitors": ["HP", "Lenovo", "Apple", "ASUS", "Acer",
                        "Microsoft Surface", "Samsung", "MSI", "Razer",
                        "Framework", "LG Gram"],
        "price_anchors": ["under $400", "under $500", "under $700", "under $800",
                          "under $1000", "under $1500", "under $2000",
                          "budget", "mid range", "premium"],
        "attributes": ["battery life", "display quality", "build quality",
                       "performance", "weight", "keyboard feel",
                       "port selection", "webcam quality", "fan noise",
                       "repairability", "warranty", "customer support",
                       "price to performance", "thermals"],
        "use_contexts": ["college coursework", "software development",
                         "gaming", "video editing", "photo editing",
                         "working from home", "graphic design",
                         "data science", "everyday use",
                         "business travel", "music production",
                         "running virtual machines"],
        "customer_types": ["college students", "business professionals",
                           "gamers", "content creators", "software developers",
                           "remote workers", "video editors", "engineers",
                           "small business owners"],
        "pain_points": ["bloatware", "fan noise", "short battery life",
                        "build feels cheap at lower price points",
                        "slow customer support", "driver issues"],
    },

    "cisco": {
        "display_name": "Cisco",
        "owned_by": "Jovana",
        "industry": "enterprise_technology",
        "competitors": ["Juniper Networks", "Aruba HPE", "Palo Alto Networks",
                        "Fortinet", "Ubiquiti", "Zoom", "Microsoft Teams",
                        "Cloudflare", "Zscaler", "SonicWall", "MikroTik",
                        "Arista Networks"],
        "price_anchors": ["SMB budget", "per user licensing", "subscription model",
                          "best value for enterprise", "total cost of ownership",
                          "perpetual license"],
        "attributes": ["reliability and uptime", "ease of management",
                       "security features", "scalability",
                       "cloud management", "technical support quality",
                       "integration with existing tools",
                       "API and automation support",
                       "licensing clarity", "throughput performance"],
        "use_contexts": ["setting up a small office network",
                         "securing remote workers",
                         "replacing aging network hardware",
                         "SD WAN deployment",
                         "zero trust security rollout",
                         "video conferencing infrastructure",
                         "cloud migration networking",
                         "VPN for remote access",
                         "compliance and audit readiness",
                         "wireless in a warehouse"],
        "customer_types": ["enterprise IT teams", "network administrators",
                           "small business IT managers",
                           "managed service providers",
                           "government IT", "healthcare IT",
                           "university network teams"],
        "pain_points": ["licensing too complex", "too expensive for small business",
                        "slow support tickets", "hardware end of life too soon",
                        "steep learning curve", "subscription costs adding up"],
    },

    "nfl": {
        "display_name": "NFL",
        "owned_by": "Jaheim",
        "industry": "sports_entertainment",
        "competitors": ["NBA", "MLB", "NHL", "MLS", "Premier League",
                        "UFC", "NCAA Football", "ESPN Plus",
                        "YouTube TV", "Hulu Live", "FuboTV",
                        "Peacock", "Amazon Prime Video"],
        "price_anchors": ["free", "under $10 a month", "under $50",
                          "annual plan", "bundle deal", "student discount"],
        "attributes": ["streaming quality", "game coverage",
                       "blackout restrictions", "fantasy football tools",
                       "injury report accuracy", "highlights availability",
                       "app experience", "RedZone access", "stats depth"],
        "use_contexts": ["watching out of market games",
                         "cutting the cord but keeping football",
                         "playing fantasy football",
                         "sports betting research",
                         "watching the Super Bowl",
                         "following the NFL Draft",
                         "tracking trades and free agency",
                         "catching game highlights",
                         "watching Thursday Night Football"],
        "customer_types": ["die hard football fans", "fantasy football players",
                           "sports bettors", "cord cutters", "families",
                           "out of market fans", "international NFL fans",
                           "casual viewers"],
        "pain_points": ["blackout restrictions", "too expensive",
                        "app keeps buffering", "no RedZone on basic plan",
                        "Sunday Ticket price too high"],
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# SEARCHER PERSONAS
#
# 8 archetypes, each with branded + unbranded pattern pools.
# Weights determine how often each persona is picked.
#
# A persona's patterns define both the PHRASING STYLE and INTENT.
# This is what creates genuine variety — not just shuffling the same 5 templates.
# ─────────────────────────────────────────────────────────────────────────────

PERSONAS = {

    "quick_buyer": {
        "weight": 0.20,
        "description": "Short, decisive, price-focused fragments",
        "branded_patterns": [
            "{brand} {product} {price}",
            "best {brand} {product}",
            "buy {brand} {product} {price}",
            "{brand} {product} {year}",
            "{brand} {product} worth it",
            "good {brand} {product} for {customer}",
            "{brand} {product} under {price}",
            "{brand} {product} deal",
            "{brand} {product} sale",
            "{brand} {product} cheap",
        ],
        "unbranded_patterns": [
            "best {product} {price}",
            "{product} {price} {year}",
            "buy {product} under {price}",
            "top {product} right now",
            "best {product} {year}",
            "cheap {product} that actually works",
            "{product} for {customer}",
            "best {product} for {use_context}",
            "good {product} under {price}",
            "{product} worth buying {year}",
        ],
    },

    "researcher": {
        "weight": 0.18,
        "description": "Full questions, thorough, comparison-oriented",
        "branded_patterns": [
            "what is the best {brand} {product} for {use_context}",
            "which {brand} {product} should I get for {customer}",
            "is {brand} a good place to buy {product}",
            "how does {brand} compare for {product}",
            "{brand} {product} vs {competitor} which is better",
            "is {brand} {product} reliable",
            "what do people think of {brand} for {product}",
            "should I buy {product} from {brand} or {competitor}",
            "pros and cons of buying {product} on {brand}",
            "{brand} vs {competitor} for {product} {year}",
            "is {brand} worth it for {product}",
        ],
        "unbranded_patterns": [
            "what is the best {product} for {use_context}",
            "how to choose the right {product} for {customer}",
            "what should I look for when buying a {product}",
            "which {product} is best for {use_context}",
            "things to consider when buying {product}",
            "{product} buying guide {year}",
            "best {product} for {customer} {year}",
            "how to pick a {product} for {use_context}",
            "what makes a good {product}",
            "{product} recommendations for {customer}",
            "how do I know which {product} to buy",
        ],
    },

    "deal_hunter": {
        "weight": 0.15,
        "description": "Discount and value obsessed",
        "branded_patterns": [
            "{brand} {product} on sale",
            "cheapest {brand} {product} right now",
            "{brand} {product} discount {year}",
            "best {brand} {product} deals",
            "refurbished {product} on {brand} worth buying",
            "{brand} {product} price drop",
            "when does {brand} have sales on {product}",
            "{brand} {product} clearance",
            "used {product} on {brand} {price}",
            "{brand} {product} coupon {year}",
        ],
        "unbranded_patterns": [
            "cheap {product} that are actually good {year}",
            "{product} under {price} worth buying",
            "best {product} deals right now",
            "refurbished {product} worth it",
            "best time to buy a {product}",
            "where to find cheap {product} online",
            "open box {product} worth it",
            "{product} {price} — is it good",
            "best budget {product} {year}",
            "discount {product} that dont suck",
            "best value {product} for the money {year}",
        ],
    },

    "skeptic": {
        "weight": 0.15,
        "description": "Looking for problems, scams, red flags",
        "branded_patterns": [
            "is {brand} safe to buy {product} from",
            "{brand} {product} problems",
            "what are the downsides of {brand} for {product}",
            "is {brand} trustworthy for {product}",
            "{brand} {product} scam or legit",
            "has anyone been scammed buying {product} on {brand}",
            "why is {brand} {product} so cheap",
            "red flags when buying {product} on {brand}",
            "honest {brand} {product} review {year}",
            "{brand} {product} after 6 months — still good",
            "is {brand} {product} worth the money honestly",
            "{brand} {product} too good to be true",
        ],
        "unbranded_patterns": [
            "common problems with {product} {year}",
            "things to watch out for when buying {product}",
            "{product} red flags to avoid",
            "are cheap {product} worth buying",
            "most common {product} complaints",
            "what nobody tells you about buying {product}",
            "mistakes people make buying {product}",
            "{product} buying mistakes to avoid {year}",
            "signs of a fake {product}",
            "is a refurbished {product} worth the risk",
            "why do {product} fail so fast",
        ],
    },

    "casual_browser": {
        "weight": 0.12,
        "description": "Vague, exploratory, not sure what they want",
        "branded_patterns": [
            "{brand} {product}",
            "{brand} for {product}",
            "{brand} {product} any good",
            "{brand} {product} thoughts",
            "anyone use {brand} for {product}",
            "{brand} good for {product}",
            "what do people think of {brand} {product}",
            "heard about {brand} {product}",
        ],
        "unbranded_patterns": [
            "{product} options {year}",
            "good {product} recommendations",
            "what {product} do people like",
            "popular {product} right now",
            "trending {product} {year}",
            "top {product} everyone is talking about",
            "{product} worth trying",
            "whats a good {product}",
            "need a {product} suggestions",
        ],
    },

    "experienced_user": {
        "weight": 0.10,
        "description": "Knows terminology, specific requirements",
        "branded_patterns": [
            "{brand} {product} {attribute}",
            "how good is {brand} {product} {attribute}",
            "{brand} {product} specs vs {competitor}",
            "does {brand} {product} have good {attribute}",
            "{brand} {product} for {use_context} — worth it",
            "which {brand} {product} model is best for {use_context}",
            "upgrading to {brand} {product} from {competitor}",
            "{brand} {product} differences between models {year}",
            "best {brand} {product} for {use_context} {year}",
        ],
        "unbranded_patterns": [
            "best {product} {attribute} {year}",
            "{product} with the best {attribute}",
            "which {product} has the best {attribute}",
            "top {product} for {use_context} with good {attribute}",
            "{product} for {use_context} — {attribute} comparison",
            "best {product} for {customer} who needs {attribute}",
            "{product} {attribute} tier list {year}",
        ],
    },

    "reddit_searcher": {
        "weight": 0.05,
        "description": "Appends reddit, community driven",
        "branded_patterns": [
            "{brand} {product} reddit",
            "best {brand} {product} reddit {year}",
            "{brand} {product} review reddit",
            "anyone bought {product} on {brand} reddit",
            "{brand} worth it for {product} reddit",
            "{brand} vs {competitor} {product} reddit",
            "{brand} {product} recommendations reddit",
        ],
        "unbranded_patterns": [
            "best {product} reddit {year}",
            "{product} recommendations reddit",
            "best {product} for {customer} reddit",
            "{product} for {use_context} reddit",
            "what {product} do you use reddit",
            "honest {product} review reddit {year}",
            "{product} megathread {year} reddit",
        ],
    },

    "frustrated_buyer": {
        "weight": 0.05,
        "description": "Has had issues, wants alternatives",
        "branded_patterns": [
            "why is {brand} {product} so overpriced",
            "{brand} {product} not worth it anymore",
            "alternatives to {brand} for {product}",
            "better than {brand} for {product}",
            "leaving {brand} — best {product} alternatives",
            "is {brand} {product} getting worse",
            "switched from {brand} to {competitor} for {product} — was it worth it",
            "{brand} {product} disappointing",
        ],
        "unbranded_patterns": [
            "why is {product} so expensive now",
            "affordable {product} alternatives {year}",
            "better {product} options that arent overpriced",
            "underrated {product} brands worth trying",
            "hidden gem {product} {year}",
            "best {product} for people who are tired of {pain_point}",
            "why cant I find a good {product} anymore",
        ],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# COMPETITOR MENTION TEMPLATES (always branded, brand appears once)
# ─────────────────────────────────────────────────────────────────────────────

COMPETITOR_PATTERNS = [
    "{brand} vs {competitor} {product} which is better",
    "is {brand} or {competitor} better for {product}",
    "{brand} {product} compared to {competitor}",
    "people who switched from {competitor} to {brand} for {product}",
    "{brand} vs {competitor} for {product} {year}",
    "why I chose {brand} over {competitor} for {product}",
    "should I use {brand} or {competitor} for {product}",
    "{competitor} vs {brand} {product} honest comparison",
    "switched from {competitor} to {brand} for {product} — worth it",
    "{brand} {product} vs {competitor} pros and cons",
    "is {brand} still better than {competitor} for {product} {year}",
]


# ─────────────────────────────────────────────────────────────────────────────
# HUMAN IMPERFECTION LAYER
# ~15% of queries get realistic imperfections: typos, lowercase, slang
# ─────────────────────────────────────────────────────────────────────────────

COMMON_TYPOS = {
    "laptop": ["laaptop", "laptoop", "lapttop", "latop"],
    "phone": ["pnone", "phon", "fone"],
    "mobile": ["moblie", "mobil", "moble"],
    "credit": ["creditt", "creidt"],
    "router": ["routre", "rotuer"],
    "review": ["reveiw", "reviwe"],
    "buying": ["buyng", "buiyng"],
    "budget": ["budjet", "budgt"],
    "reliable": ["reliabel"],
    "refurbished": ["refurb", "refurbrished"],
    "warranty": ["warrenty", "warrany"],
    "recommendations": ["reccomendations", "recomendations", "recs"],
}

CASUAL_SUFFIXES = [" tbh", " honestly", " ngl", " thoughts", " anyone", " help"]


def _apply_human_layer(text: str, rng: random.Random) -> str:
    """Apply probabilistic human imperfections to a query string."""

    # 8% chance: introduce a typo
    if rng.random() < 0.08:
        words = text.split()
        for word_lower, typos in COMMON_TYPOS.items():
            for i, w in enumerate(words):
                if w.lower() == word_lower and rng.random() < 0.5:
                    words[i] = rng.choice(typos)
                    text = " ".join(words)
                    break

    # 7% chance: add casual suffix
    if rng.random() < 0.07:
        text = text + rng.choice(CASUAL_SUFFIXES)

    # 30% chance: lowercase (real searchers often don't capitalize)
    if rng.random() < 0.30:
        text = text.lower()

    return " ".join(text.split()).strip()


# ─────────────────────────────────────────────────────────────────────────────
# RESULT DATACLASS
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class GeneratedQuery:
    """A single generated search query with full metadata."""
    text: str
    is_branded: bool
    bucket: str           # "branded" | "unbranded" | "competitor"
    persona: str          # which searcher persona generated this
    company: str
    product_topic: str
    slots: dict = field(default_factory=dict)

    def __str__(self) -> str:
        return f"[{self.bucket:10s}|{self.persona:18s}] {self.text}"


# ─────────────────────────────────────────────────────────────────────────────
# CORE GENERATION FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def generate_queries(
    company_name: str,
    product: str,
    num_queries: int = 50,
    branded_weight: float = 0.70,
    unbranded_weight: float = 0.25,
    competitor_weight: float = 0.05,
    human_imperfection: bool = True,
    seed: Optional[int] = None,
) -> list[GeneratedQuery]:
    """
    Generate realistic consumer search queries for brand visibility monitoring.

    Every query is shaped by the `product` argument — pass "mobile" and every
    query is about mobiles, with eBay (or your brand) appearing naturally.

    Queries come from 8 searcher personas (quick_buyer, researcher,
    deal_hunter, skeptic, casual_browser, experienced_user, reddit_searcher,
    frustrated_buyer) — each with distinct phrasing styles, producing genuine
    variety rather than cycling through a fixed list.

    Args:
        company_name:       Supported keys: "capital one", "ebay", "heb",
                            "home depot", "dell", "cisco", "nfl"
        product:            Topic for every query. E.g. "mobile", "laptop",
                            "credit card", "router", "streaming"
        num_queries:        Total queries to generate.
        branded_weight:     Share including brand name. Default 0.70.
        unbranded_weight:   Share generic/no brand. Default 0.25.
        competitor_weight:  Share mentioning competitor vs brand. Default 0.05.
        human_imperfection: Add realistic typos/lowercase/slang. Default True.
        seed:               Int for reproducible output. None = random.

    Returns:
        List[GeneratedQuery] — access .text for the query string.

    Example output for generate_queries("ebay", "mobile", 10):
        is eBay safe to buy mobile from
        best mobile under $200 2026
        eBay vs Swappa mobile which is better
        cheap mobile that actually works
        ebay mobile any good
        refurbished mobile on eBay worth buying
        what is the best mobile for buying a refurbished phone
        eBay mobile problems
        best mobile deals right now
        eBay mobile reddit
    """

    key = company_name.strip().lower()
    if key not in COMPANY_PROFILES:
        available = ", ".join(sorted(COMPANY_PROFILES.keys()))
        raise ValueError(f"Unknown company '{company_name}'. Available: {available}")

    total_w = branded_weight + unbranded_weight + competitor_weight
    if not (0.98 <= total_w <= 1.02):
        raise ValueError(f"Weights must sum to 1.0 (got {total_w:.2f})")

    profile = COMPANY_PROFILES[key]
    rng = random.Random(seed if seed is not None else time.time())
    year = time.strftime("%Y")

    n_branded    = round(num_queries * branded_weight)
    n_unbranded  = round(num_queries * unbranded_weight)
    n_competitor = num_queries - n_branded - n_unbranded

    persona_names   = list(PERSONAS.keys())
    persona_weights = [PERSONAS[p]["weight"] for p in persona_names]

    def _pick(lst: list) -> str:
        return rng.choice(lst) if lst else ""

    def _safe_competitor() -> str:
        brand = profile["display_name"].lower()
        for _ in range(15):
            c = _pick(profile["competitors"])
            if brand not in c.lower():
                return c
        return _pick(profile["competitors"])

    def _fill(template: str) -> tuple[str, dict]:
        slots: dict = {}
        r = template

        if "{brand}" in r:
            r = r.replace("{brand}", profile["display_name"])
            slots["brand"] = profile["display_name"]

        if "{product}" in r:
            r = r.replace("{product}", product)
            slots["product"] = product

        if "{competitor}" in r:
            c = _safe_competitor()
            r = r.replace("{competitor}", c)
            slots["competitor"] = c

        if "{price}" in r:
            if "under {price}" in template:
                pool = [p for p in profile["price_anchors"] if any(ch.isdigit() for ch in p)]
                pool = pool or profile["price_anchors"]
                price = _pick(pool)
                if price.lower().startswith("under "):
                    price = price[6:]
            else:
                price = _pick(profile["price_anchors"])
            r = r.replace("{price}", price)
            slots["price"] = price

        if "{attribute}" in r:
            a = _pick(profile["attributes"])
            r = r.replace("{attribute}", a)
            slots["attribute"] = a

        if "{use_context}" in r:
            u = _pick(profile["use_contexts"])
            r = r.replace("{use_context}", u)
            slots["use_context"] = u

        if "{customer}" in r:
            c2 = _pick(profile["customer_types"])
            r = r.replace("{customer}", c2)
            slots["customer"] = c2

        if "{pain_point}" in r:
            p = _pick(profile.get("pain_points", ["overpriced"]))
            r = r.replace("{pain_point}", p)
            slots["pain_point"] = p

        if "{year}" in r:
            r = r.replace("{year}", year)

        return " ".join(r.split()).strip(), slots

    def _make_one(bucket: str) -> Optional[GeneratedQuery]:
        persona_name = rng.choices(persona_names, weights=persona_weights, k=1)[0]
        persona = PERSONAS[persona_name]

        if bucket == "competitor":
            template = _pick(COMPETITOR_PATTERNS)
        elif bucket == "branded":
            template = _pick(persona["branded_patterns"])
        else:
            template = _pick(persona["unbranded_patterns"])

        text, slots = _fill(template)

        if human_imperfection:
            text = _apply_human_layer(text, rng)

        return GeneratedQuery(
            text=text,
            is_branded=(bucket != "unbranded"),
            bucket=bucket,
            persona=persona_name,
            company=profile["display_name"],
            product_topic=product,
            slots=slots,
        )

    def _fill_bucket(count: int, bucket: str) -> list[GeneratedQuery]:
        results: list[GeneratedQuery] = []
        seen: set[str] = set()
        attempts = 0
        while len(results) < count and attempts < count * 25:
            attempts += 1
            q = _make_one(bucket)
            if q is None:
                continue
            dedup = q.text.lower().strip()
            if dedup in seen:
                continue
            seen.add(dedup)
            results.append(q)
        return results

    all_queries = (
        _fill_bucket(n_branded, "branded") +
        _fill_bucket(n_unbranded, "unbranded") +
        _fill_bucket(n_competitor, "competitor")
    )

    rng.shuffle(all_queries)
    return all_queries[:num_queries]


# ─────────────────────────────────────────────────────────────────────────────
# UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

def get_supported_companies() -> list[tuple[str, str, str]]:
    """Return list of (key, display_name, owned_by) tuples."""
    return [(k, v["display_name"], v["owned_by"]) for k, v in COMPANY_PROFILES.items()]


def summarize(queries: list[GeneratedQuery]) -> dict:
    """Distribution summary for a generated batch."""
    total = len(queries)
    buckets: dict[str, int] = {}
    personas: dict[str, int] = {}
    for q in queries:
        buckets[q.bucket] = buckets.get(q.bucket, 0) + 1
        personas[q.persona] = personas.get(q.persona, 0) + 1

    return {
        "total": total,
        "buckets": buckets,
        "personas": dict(sorted(personas.items(), key=lambda x: -x[1])),
        "branded_pct": round(100 * buckets.get("branded", 0) / total) if total else 0,
        "unbranded_pct": round(100 * buckets.get("unbranded", 0) / total) if total else 0,
        "competitor_pct": round(100 * buckets.get("competitor", 0) / total) if total else 0,
        "company": queries[0].company if queries else None,
        "product_topic": queries[0].product_topic if queries else None,
    }


# ─────────────────────────────────────────────────────────────────────────────
# SMOKE TEST
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import json

    print("=" * 70)
    print("TEST: eBay + mobile  (the exact failing case from the UI)")
    print("=" * 70)
    queries = generate_queries("ebay", "mobile", num_queries=30, seed=99)
    for i, q in enumerate(queries, 1):
        print(f"  #{i:02d}  {q.text}")

    s = summarize(queries)
    print(f"\n  Branded {s['branded_pct']}%  Unbranded {s['unbranded_pct']}%  Competitor {s['competitor_pct']}%")
    print(f"  Personas: {json.dumps(s['personas'])}")

    print()
    print("=" * 70)
    print("TEST: Dell + laptop")
    print("=" * 70)
    queries2 = generate_queries("dell", "laptop", num_queries=15, seed=7)
    for i, q in enumerate(queries2, 1):
        print(f"  #{i:02d}  {q.text}")

    print()
    print("=" * 70)
    print("TEST: Capital One + credit card")
    print("=" * 70)
    queries3 = generate_queries("capital one", "credit card", num_queries=10, seed=1)
    for i, q in enumerate(queries3, 1):
        print(f"  #{i:02d}  {q.text}")