from app.extensions import db
from datetime import datetime, timezone
import enum


class Competitor(db.Model):
    """
    A competitor brand that Vigil tracks for a given company.
    Home Depot tracks Lowe's and Amazon.
    Capital One tracks Chase and Discover.
    Vigil runs the same queries for competitors to build comparison tables.
    """
    __tablename__ = "competitors"

    id             = db.Column(db.Integer, primary_key=True)
    company_id     = db.Column(db.Integer, db.ForeignKey("companies.id"), nullable=False)
    # Which of our companies is doing the tracking

    name           = db.Column(db.String(100), nullable=False)
    # e.g. "Lowe's", "Amazon", "Chase", "Discover"

    slug           = db.Column(db.String(50), nullable=False)
    # e.g. "lowes", "amazon", "chase" — used in API responses

    primary_domain = db.Column(db.String(255))
    # e.g. "https://www.lowes.com" — used to identify citations in AI responses

    logo_url       = db.Column(db.String(500))

    is_active      = db.Column(db.Boolean, default=True)
    # Inactive competitors are excluded from ranking runs

    created_at     = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    company  = db.relationship("Company", back_populates="competitors")
    rankings = db.relationship("CompetitorRanking", back_populates="competitor", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Competitor {self.name} vs company_id={self.company_id}>"

    def to_dict(self):
        return {
            "id":             self.id,
            "company_id":     self.company_id,
            "name":           self.name,
            "slug":           self.slug,
            "primary_domain": self.primary_domain,
            "logo_url":       self.logo_url,
            "is_active":      self.is_active,
        }


class CompetitorRanking(db.Model):
    """
    One data point: for one query run, what was each competitor's AI ranking
    compared to our company?
    Powers the competitor ranking table and content gap analysis on the dashboard.
    """
    __tablename__ = "competitor_rankings"

    id                 = db.Column(db.Integer, primary_key=True)
    competitor_id      = db.Column(db.Integer, db.ForeignKey("competitors.id"), nullable=False)
    query_run_id       = db.Column(db.Integer, db.ForeignKey("query_runs.id"), nullable=False)
    company_id         = db.Column(db.Integer, db.ForeignKey("companies.id"), nullable=False)

    # Head-to-head positioning in the AI response
    our_position       = db.Column(db.Integer)
    # Where our company ranked in this query run (null = not mentioned)

    their_position     = db.Column(db.Integer)
    # Where this competitor ranked in the same query run (null = not mentioned)

    our_mentioned      = db.Column(db.Boolean, default=False)
    their_mentioned    = db.Column(db.Boolean, default=False)

    they_were_cited_from = db.Column(db.JSON, default=list)
    # List of source URLs AI used when referencing this competitor
    # e.g. ["thepoints guy.com/...", "reddit.com/r/creditcards/..."]
    # Reveals content the competitor has that we don't (content gap)

    we_were_cited_from = db.Column(db.JSON, default=list)
    # Source URLs AI used when referencing our company in this same run

    content_gap_notes  = db.Column(db.Text)
    # Auto-generated by root_cause.py — plain English explanation
    # of WHY the competitor ranked higher and what content we're missing
    # e.g. "Lowe's has a dedicated beginner tool guide that ranks #1 for
    # 'tools for beginners'; Home Depot has no equivalent page."

    recorded_at        = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    competitor = db.relationship("Competitor", back_populates="rankings")
    query_run  = db.relationship("QueryRun")
    company    = db.relationship("Company")

    def __repr__(self):
        return f"<CompetitorRanking competitor={self.competitor_id} our={self.our_position} their={self.their_position}>"

    def to_dict(self):
        return {
            "id":                    self.id,
            "competitor_id":         self.competitor_id,
            "query_run_id":          self.query_run_id,
            "our_position":          self.our_position,
            "their_position":        self.their_position,
            "our_mentioned":         self.our_mentioned,
            "their_mentioned":       self.their_mentioned,
            "they_were_cited_from":  self.they_were_cited_from,
            "content_gap_notes":     self.content_gap_notes,
            "recorded_at":           self.recorded_at.isoformat() if self.recorded_at else None,
        }
