"""initial schema auth and run history

Revision ID: ea89abdb4d05
Revises: 
Create Date: 2026-03-12 18:39:52.121500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea89abdb4d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('industry_type', sa.Enum('RETAIL', 'FINANCIAL', 'TECHNOLOGY', 'MEDIA_SPORTS', 'GROCERY', name='industrytype'), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=False),
    sa.Column('about_company', sa.Text(), nullable=True),
    sa.Column('approved_email_domain', sa.String(length=255), nullable=True),
    sa.Column('registration_status', sa.String(length=30), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('ai_visibility_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('top_rec_rate', sa.Float(), nullable=True),
    sa.Column('open_error_count', sa.Integer(), nullable=True),
    sa.Column('bot_allowed', sa.Boolean(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_queried_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('citation_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('COMPANY_OWNED', 'NEWS', 'REVIEW_SITE', 'FORUM', 'SOCIAL', 'COMPETITOR', 'AGGREGATOR', 'WIKI', 'GOVERNMENT', name='sourcetype'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('accuracy_concern', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('enabled_platforms', sa.JSON(), nullable=True),
    sa.Column('priority_pages', sa.JSON(), nullable=True),
    sa.Column('compliance_mode', sa.Boolean(), nullable=True),
    sa.Column('alert_email', sa.String(length=255), nullable=True),
    sa.Column('default_query_count', sa.Integer(), nullable=True),
    sa.Column('max_query_count', sa.Integer(), nullable=True),
    sa.Column('auto_approve_domain_logins', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('company_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_users_email'), ['email'], unique=False)

    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='crawlstatus'), nullable=True),
    sa.Column('pages_found', sa.Integer(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('pages_failed', sa.Integer(), nullable=True),
    sa.Column('bot_blocked', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCT_RECOMMENDATION', 'PRODUCT_FACT', 'COMPETITOR_COMPARISON', 'POLICY_QUESTION', 'BRAND_GENERAL', 'USE_CASE', name='querycategory'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('expected_brand_mention', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('requested_from_ip', sa.String(length=100), nullable=True),
    sa.Column('requested_user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('page_type', sa.Enum('PRODUCT_PAGE', 'CATEGORY_PAGE', 'LANDING_PAGE', 'FAQ_PAGE', 'POLICY_PAGE', 'BLOG_POST', 'COMPARISON', 'HOMEPAGE', name='pagetype'), nullable=True),
    sa.Column('bot_readable_text', sa.Text(), nullable=True),
    sa.Column('human_readable_text', sa.Text(), nullable=True),
    sa.Column('content_delta', sa.Text(), nullable=True),
    sa.Column('content_delta_score', sa.Float(), nullable=True),
    sa.Column('has_schema', sa.Boolean(), nullable=True),
    sa.Column('has_valid_schema', sa.Boolean(), nullable=True),
    sa.Column('schema_types_found', sa.JSON(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('word_count_bot', sa.Integer(), nullable=True),
    sa.Column('word_count_human', sa.Integer(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_batch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', name='batchsource'), nullable=True),
    sa.Column('product_topic', sa.String(length=255), nullable=False),
    sa.Column('requested_query_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='batchstatus'), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('completed_queries', sa.Integer(), nullable=True),
    sa.Column('failed_queries', sa.Integer(), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('summary_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('mention_rate', sa.Float(), nullable=True),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('top_position_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['query_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_from_ip', sa.String(length=100), nullable=True),
    sa.Column('created_user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('edited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('prompt_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='batchitemstatus'), nullable=True),
    sa.Column('item_summary', sa.JSON(), nullable=True),
    sa.Column('item_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_run_id'], ['query_batch_runs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['company_users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['query_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_audit_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('MISSING_TYPE', 'MISSING_FIELD', 'INVALID_VALUE', 'OUTDATED_PRICE', 'DUPLICATE_SCHEMA', 'WRONG_TYPE', name='schemaissuetype'), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_fixable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_audit_id'], ['page_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.Column('batch_item_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('CHATGPT', 'GEMINI', 'PERPLEXITY', 'CLAUDE', name='llmplatform'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=True),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('citations_found', sa.JSON(), nullable=True),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_item_id'], ['query_batch_items.id'], ),
    sa.ForeignKeyConstraint(['batch_run_id'], ['query_batch_runs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['query_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accuracy_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_run_id', sa.Integer(), nullable=False),
    sa.Column('live_page_url', sa.String(length=500), nullable=True),
    sa.Column('live_page_snapshot', sa.Text(), nullable=True),
    sa.Column('claims_checked', sa.Integer(), nullable=True),
    sa.Column('claims_correct', sa.Integer(), nullable=True),
    sa.Column('claims_wrong', sa.Integer(), nullable=True),
    sa.Column('overall_accurate', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_run_id')
    )
    op.create_table('competitor_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('query_run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('our_position', sa.Integer(), nullable=True),
    sa.Column('their_position', sa.Integer(), nullable=True),
    sa.Column('our_mentioned', sa.Boolean(), nullable=True),
    sa.Column('their_mentioned', sa.Boolean(), nullable=True),
    sa.Column('they_were_cited_from', sa.JSON(), nullable=True),
    sa.Column('we_were_cited_from', sa.JSON(), nullable=True),
    sa.Column('content_gap_notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethics_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('query_run_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('FINANCIAL_MISINFORMATION', 'HEALTH_MISINFORMATION', 'DISCRIMINATORY_CONTENT', 'PRIVACY_VIOLATION', 'MISLEADING_COMPARISON', 'UNDISCLOSED_LIMITATION', 'REGULATORY_BREACH', name='ethicscategory'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ethicsseverity'), nullable=False),
    sa.Column('alert_status', sa.Enum('OPEN', 'ALERTED', 'REVIEWING', 'RESOLVED', 'ESCALATED', name='alertstatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_response_excerpt', sa.Text(), nullable=True),
    sa.Column('regulation_reference', sa.String(length=255), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('alerted_at', sa.DateTime(), nullable=True),
    sa.Column('alerted_to', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('query_run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cited_url', sa.String(length=1000), nullable=True),
    sa.Column('citation_context', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('caused_error', sa.Boolean(), nullable=True),
    sa.Column('mentioned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['citation_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethics_flag_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sent_to', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['ethics_flag_id'], ['ethics_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factual_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy_check_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.Enum('WRONG_PRICE', 'WRONG_SPEC', 'WRONG_POLICY', 'WRONG_AVAILABILITY', 'WRONG_REWARDS', 'DISCONTINUED_PRODUCT', 'WRONG_FEE', 'HALLUCINATED_FEATURE', name='errortype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='errorseverity'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('ai_stated_value', sa.Text(), nullable=True),
    sa.Column('correct_value', sa.Text(), nullable=True),
    sa.Column('source_page_url', sa.String(length=500), nullable=True),
    sa.Column('root_cause', sa.Enum('JS_HIDDEN_CONTENT', 'INVALID_SCHEMA', 'MISSING_SCHEMA', 'THIRD_PARTY_SOURCE', 'STALE_CONTENT', 'BOT_BLOCKED', 'CONTENT_GAP', 'TRAINING_DATA', name='rootcause'), nullable=True),
    sa.Column('root_cause_detail', sa.Text(), nullable=True),
    sa.Column('third_party_source', sa.String(length=255), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('compliance_risk', sa.Boolean(), nullable=True),
    sa.Column('compliance_flag_sent', sa.Boolean(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accuracy_check_id'], ['accuracy_checks.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('factual_error_id', sa.Integer(), nullable=True),
    sa.Column('fix_type', sa.Enum('USE_CASE_BLOCK', 'SCHEMA_PATCH', 'FACT_CORRECTION', 'NEW_PAGE', 'META_UPDATE', 'ROBOTS_INSTRUCTION', name='fixtype'), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'APPROVED', 'PUBLISHED', 'REJECTED', 'SUPERSEDED', name='fixstatus'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('target_page_url', sa.String(length=1000), nullable=True),
    sa.Column('target_queries', sa.JSON(), nullable=True),
    sa.Column('estimated_impact', sa.Float(), nullable=True),
    sa.Column('effort_level', sa.String(length=20), nullable=True),
    sa.Column('before_score', sa.Float(), nullable=True),
    sa.Column('after_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['factual_error_id'], ['factual_errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_fix_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('published_content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.String(length=100), nullable=True),
    sa.Column('impact_measured', sa.Boolean(), nullable=True),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('measurement_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['content_fix_id'], ['content_fixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_fixes')
    op.drop_table('content_fixes')
    op.drop_table('factual_errors')
    op.drop_table('compliance_alerts')
    op.drop_table('source_mentions')
    op.drop_table('ethics_flags')
    op.drop_table('competitor_rankings')
    op.drop_table('accuracy_checks')
    op.drop_table('query_runs')
    op.drop_table('schema_issues')
    op.drop_table('query_batch_items')
    op.drop_table('user_sessions')
    op.drop_table('query_results')
    op.drop_table('query_batch_runs')
    op.drop_table('page_audits')
    op.drop_table('magic_link_tokens')
    op.drop_table('query_templates')
    op.drop_table('crawl_jobs')
    op.drop_table('competitors')
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_users_email'))

    op.drop_table('company_users')
    op.drop_table('company_domains')
    op.drop_table('company_configs')
    op.drop_table('citation_sources')
    op.drop_table('companies')
    # ### end Alembic commands ###
